language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - 2.0.0
  - rbx-18mode
  - rbx-19mode
  - ruby-head


script: "bundle exec rake test:local"

matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: rbx-18mode
    - rvm: ruby-head

notifications:
  email:
    on_success: always
